### ISSUE TITLE
Not Able to start when ASYNCHRONOUS data is fed from state..

### ISSUE THREAD

**Issue by 9jaydoshi9** [CoderSau/react-flexy-table#9]
Hi,

When I get data from **API** using fetch and changing the state, it gives cannot do **toString() of undefined**.
I have checked **my data** and it **is fine** (i.e not undefined)..

Ref : https://pastebin.com/tLZKuSdW

**Comment by CoderSau** [comment]
hi 9 jaydesh9,
thanks for that feedback. This bug resolved in version 1.4.6. could update your version and try again?

**Comment by 9jaydoshi9** [comment]
hello,
I updated and found out that **search is not working anywhere** in version 1.4.6.
Although the previous problem was solved in the update..

**Comment by CoderSau** [comment]
hi 9jaydoshi9,

 I've fix this bug  in version 1.5.6. Please let me know if you find any other bugs.

Thanks

**Comment by 9jaydoshi9** [comment]
Hey,
Sorry to notify but the previous bug **"Not Able to start when ASYNCHRONOUS data is fed from state"** is not solved in this one.
Although I am able to search but not able to fetch data.

**Comment by CoderSau** [comment]
hey,

I'm sorry, it's my fault I couldn find to correct way to solve this problem. But finaly I believe the bug solved in version 1.5.8 . I've also try this in a real project and it seem like okey. if you have any other problem please let me know.

thanks

**Comment by 9jaydoshi9** [comment]
Thanks for the support.
I'll let you know if I find anything else.
